import Head from "next/head";

import BasicLayout from "~/components/BasicLayout";
import DashboardDisplay from "~/components/DashboardDisplay";
import { api } from "~/utils/api";

const Dashboard = () => {
  const { data, isLoading } = api.boards.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>404</div>;

  return (
    <>
      <Head>
        <title>Kanvas - Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BasicLayout>
        <DashboardDisplay data={data}/>
      </BasicLayout>
    </>
  );
};

export default Dashboard;
