import Head from "next/head";

import BasicLayout from "~/components/BasicLayout";

const Dashboard = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BasicLayout>
        <div>Dashboard</div>
      </BasicLayout>
    </>
  );
};

export default Dashboard;
