import Head from "next/head";
import { useState } from "react";
import { AppShell, Navbar, Text, useMantineTheme } from "@mantine/core";
import { api } from "~/utils/api";
import SingleTask from "~/components/SingleTask";
import AppHeader from "~/components/AppHeader";

 const Dashboard = () =>{
  const theme = useMantineTheme();
  const [opened, setOpened] = useState(false);
  const { data } = api.tasks.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell
        styles={{
          main: {
            background:
              theme.colorScheme === "dark"
                ? theme.colors.dark[6]
                : theme.colors.gray[0],
          },
        }}
        navbarOffsetBreakpoint="sm"
        asideOffsetBreakpoint="sm"
        navbar={
          <Navbar
            p="md"
            hiddenBreakpoint="sm"
            hidden={!opened}
            width={{ sm: 200, lg: 300 }}
          >
            <Text>Application navbar</Text>
          </Navbar>
        }
        header={<AppHeader />}
      >
        {data?.map(({ task, author }) => (
          <SingleTask key={task.id} task={task} author={author} />
        ))}
      </AppShell>
    </>
  );
}

export default Dashboard
